name: Check site
on: [push, pull_request]
permissions:
  contents: read
jobs:
  links-and-previews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 check_site.py
